### PR TITLE
fix performance switching

### PR DESCRIPTION
**Pull request by aagu**
Although the character "_" won't cause a compilation error but performance switching won't work

### CODE REVIEW

**Comment by xuefer** [comment]
We have "setprop sys.perf.profile_ ${sys.perf.profile}" which should trigger "on property:sys.perf.profile_=high/middle/low" indirectly

are you sure it still won't work? one of the older version was not working but we have the current one working good

**Comment by aagu** [comment]
You can check CM's repository,like this one https://github.com/CyanogenMod/android_device_xiaomi_cancro/blob/cm-12.1/rootdir/root/init.target.rc
there is no "_" after sys.perf.profile=0/1/2

**Comment by xuefer** [comment]
there is no _ after sys.perf.profile in our rc file, see
on property:sys.perf.profile=*
and it redirect to sys.perf.profile_
    setprop sys.perf.profile_ ${sys.perf.profile}

we have both  sys.perf.profile AND  sys.perf.profile_ variable

**Comment by aagu** [comment]
So,please check if TD's cm12 could switch performance,use benchmark to exam CPU profile

**Comment by xuefer** [comment]
i did

watch 'cat /sys/devices/system/cpu/cpufreq/interactive/target_loads; getprop | grep perf'

Every 2s: cat /sys/devices/system/cpu/cpufreq/interactive/target_loads; getprop | grep perf  
75 228000:85 816000:90 1530000:95

75 228000:85 816000:90 1530000:95

55 228000:65 1530000:75

it will change accordinaly

**Pull request closed without merging**
